#!/bin/bash
#
# Make mark
#

MARKFILE="grp2_o20.mark"
#MARKFILE=$1

DIR=/smaug/data/theorie/justin/Thickdisc/Oscar_cosmo
CMD="$HOME/zTools/bin/tdump --markfile=$MARKFILE --tipsyout=XXX.grp2.std $DIR/XXX.std"

ls $DIR/halo3.*.std \
| xargs -n 1 -iXXX basename XXX .std \
| xargs -n 1 -iXXX -t -P 32 $CMD

