#!/bin/bash

MARKFILE=$1
if [ "x$MARKFILE" == "x" ]; then
    MARKFILE="grp2_o20.mark"
fi

DIR=
FILES=$(ls /smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/halo3.*.std)
CMD="$HOME/zTools/bin/tdump --markfile=$MARKFILE --tipsyout=XXX.grp2.std XXX.std"

ls /smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/halo3.*.std \
| xargs -n 1 -iXXX basename XXX .std | xargs -P 32 -n 1 -iXXX $CMD


#for f in $FILES; do
#    nf=$(basename $f .std)
#    CMD="$HOME/zTools/bin/tdump --markfile=grp2_o20.mark --tipsyout=$nf.grp2.std $f"
#    echo $CMD
#    $CMD
#done
