#!/bin/bash

#HALOS="halo1"
#HALOS="halo1 halo2 halo4"
HALOS="halo1 halo2 halo3 halo4"

for h in $HALOS; do
    PREFIX="$h"

    if [ $h == halo1 ]; then
        DIR="/smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/AHF"
        FILES=`ls $DIR/halo1*.AHF_particles | xargs -r -I XXX basename XXX .AHF_particles | sort -r -n -t . -k2`
        NPART=4303248
    fi

    if [ $h == halo2 ]; then
        DIR="/smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/AHF"
        FILES=`ls $DIR/halo2*.AHF_particles | xargs -r -I XXX basename XXX .AHF_particles | sort -r -n -t . -k2`
        NPART=3003679
    fi

    if [ $h == halo3 ]; then
        DIR="/smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/AHF"
        FILES=`ls $DIR/halo3*.AHF_particles | xargs -r -I XXX basename XXX .AHF_particles | sort -r -n -t . -k2`
        NPART=2429427
    fi

    if [ $h == halo4 ]; then
        DIR="/smaug/data/theorie/justin/Thickdisc/Oscar_cosmo/AHF"
        FILES=`ls $DIR/halo4*.AHF_particles | xargs -r -I XXX basename XXX .AHF_particles | sort -r -n -t . -k2`
        NPART=2648284
    fi

    export DIR FILES NPART PREFIX

    (mkdir -p $h && cd $h && ../mkpf)
    (mkdir -p $h && cd $h && ../mkhtrack)
    #(mkdir -p $h && cd $h && ../mkgroups && ../mkpf && ../mkhtrack)

done

